global:
  scrape_interval: 5s # Scrape metrics every 5 seconds

scrape_configs:
  - job_name: 'harvest-web'
    metrics_path: '/api/v1/metrics'
    static_configs:
      # host.docker.internal allows the Docker container to access localhost on the Windows host machine
      - targets: ['host.docker.internal:3000']
